'use client';
import { useState } from 'react';

const events=[{day:'09',month:'OCT',artist:'MIDNIGHT / AFTER DARK',note:'OPEN FORMAT · THURSDAY',image:'https://images.pexels.com/photos/14528845/pexels-photo-14528845.jpeg?auto=compress&cs=tinysrgb&w=1400'},{day:'10',month:'OCT',artist:'SAINT NOIR',note:'HIP-HOP · FRIDAY',image:'https://images.pexels.com/photos/3867522/pexels-photo-3867522.jpeg?auto=compress&cs=tinysrgb&w=1400'},{day:'11',month:'OCT',artist:'THE SATURDAY RITUAL',note:'R&B · HIP-HOP · SATURDAY',image:'https://images.pexels.com/photos/6315389/pexels-photo-6315389.jpeg?auto=compress&cs=tinysrgb&w=1400'}];
const tables=[{id:'A1',name:'DJ Gallery',guests:8,minimum:2500,status:'available',detail:'Direct sightline to the booth. High-energy placement at the center of the room.'},{id:'A2',name:'DJ Gallery',guests:8,minimum:2500,status:'held',detail:'Direct sightline to the booth with elevated service.'},{id:'B1',name:'Noir Booth',guests:10,minimum:1800,status:'available',detail:'Elevated VIP booth with a full view of the main floor.'},{id:'B2',name:'Noir Booth',guests:10,minimum:1800,status:'available',detail:'Elevated VIP booth with a full view of the main floor.'},{id:'C1',name:'Salon',guests:6,minimum:1200,status:'reserved',detail:'Intimate lounge seating with fast access to the bar.'},{id:'C2',name:'Salon',guests:6,minimum:1200,status:'available',detail:'Intimate lounge seating with fast access to the bar.'}];
type Table=(typeof tables)[number]; type Msg={role:'ai'|'user';text:string};
export default function Home(){
const [selected,setSelected]=useState<Table|null>(null),[concierge,setConcierge]=useState(false),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[activeEvent,setActiveEvent]=useState(events[1]),[heroGuests,setHeroGuests]=useState('8'),[heroExperience,setHeroExperience]=useState('Bottle Service');
const [messages,setMessages]=useState<Msg[]>([{role:'ai',text:'Welcome to NOIR DC. Tell me the occasion, guest count, budget, or where you want to be in the room. I’ll help plan the rest.'}]);
async function send(text?:string){const value=(text||input).trim();if(!value||busy)return;setMessages(m=>[...m,{role:'user',text:value}]);setInput('');setBusy(true);try{const r=await fetch('/api/concierge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:value,event:activeEvent.artist,table:selected?.name})});const d=await r.json();setMessages(m=>[...m,{role:'ai',text:d.reply}])}catch{setMessages(m=>[...m,{role:'ai',text:'How many guests are you planning for?'}])}finally{setBusy(false)}}
function choose(t:Table){if(t.status==='reserved')return;setSelected(t)}
function heroBook(){setSelected(null);document.getElementById('reserve')?.scrollIntoView({behavior:'smooth',block:'start'})}
return (
<main>
<section className="hero"><div className="heroImage"/><div className="heroShade"/><div className="grain"/><header><a className="mark" href="#">N<span>O</span>IR</a><nav><a href="#reserve">Tables</a><a href="#reserve" onClick={()=>setHeroExperience('Bottle Service')}>Bottles</a><a href="#events">Events</a><button onClick={()=>setConcierge(true)}>VIP Concierge</button></nav></header><div className="heroCopy"><p className="eyebrow">WASHINGTON, DC · AFTER DARK</p><h1>THE NIGHT<br/><i>IS YOURS.</i></h1><p className="heroLine">A new expression of nightlife. Music, movement, and the right table.</p><div className="heroActions"><button className="heroPrimary" onClick={heroBook}>Tables & Bottle Service</button><button onClick={()=>document.getElementById('events')?.scrollIntoView({behavior:'smooth'})}>Event Tickets</button><button onClick={()=>setConcierge(true)}>VIP Concierge</button></div><div className="heroReserve"><label><span>DATE</span><select onChange={e=>setActiveEvent(events[Number(e.target.value)])} defaultValue="1">{events.map((e,i)=><option value={i} key={e.artist}>{e.month} {e.day} · {e.artist}</option>)}</select></label><label><span>GUESTS</span><select value={heroGuests} onChange={e=>setHeroGuests(e.target.value)}>{[2,4,6,8,10,12].map(n=><option key={n}>{n}</option>)}</select></label><label><span>EXPERIENCE</span><select value={heroExperience} onChange={e=>setHeroExperience(e.target.value)}><option>Bottle Service</option><option>VIP Table</option><option>Birthday</option><option>Night Out</option></select></label><button onClick={heroBook}>VIEW AVAILABLE TABLES →</button></div></div></section>
<section className="intro" id="experience"><p className="sectionNo">01 / THE EXPERIENCE</p><div><h2>DON&apos;T JUST<br/>GO <em>OUT.</em><br/><span>ARRIVE.</span></h2><div className="experiencePhoto" role="img" aria-label="Black nightlife guests enjoying the NOIR experience"></div></div><div className="introAside"><p>Built around the room, not around a screen. Discover the night, find your place, and let your private concierge handle the details.</p><button onClick={()=>setConcierge(true)}>Plan my night ↗</button></div></section>
<section className="events" id="events"><div className="sectionHead"><p>02 / UPCOMING</p><h2>THIS WEEK<br/><i>AT NOIR</i></h2><span>OCTOBER 2026</span></div><div className="eventGrid">{events.map((event,i)=><article className={i===1?'event featured':'event'} key={event.artist}><div className="eventPhoto" style={{backgroundImage:`linear-gradient(180deg,transparent 35%,rgba(0,0,0,.82)),url(${event.image})`}}></div><div className="date"><strong>{event.day}</strong><span>{event.month}</span></div><div className="eventInfo"><p>{event.note}</p><h3>{event.artist}</h3><div><button>Tickets</button><button onClick={()=>{setActiveEvent(event);setSelected(null);document.getElementById('reserve')?.scrollIntoView({behavior:'smooth'})}}>Tables</button></div></div></article>)}</div></section>
<section className="bookingExperience" id="reserve"><div className="bookingBar"><div><small>YOUR NIGHT</small><strong>{activeEvent.artist}</strong></div><div><small>DATE</small><strong>{activeEvent.month} {activeEvent.day}, 2026 · {heroGuests} GUESTS · {heroExperience.toUpperCase()}</strong></div><button onClick={()=>setConcierge(true)}>LET AI PLAN IT ↗</button></div><div className="bookingStage"><div className="mapPanel"><div className="mapTop"><span>MAIN ROOM / LIVE AVAILABILITY</span><span><i className="legend available"/> Available <i className="legend held"/> Held <i className="legend reserved"/> Reserved</span></div><div className="venueMap"><div className="djBooth">DJ BOOTH</div><div className="danceFloor">DANCE FLOOR<small>MAIN ROOM</small></div><div className="barZone">CENTER BAR</div>{tables.map((t,i)=><button key={t.id} aria-label={`${t.name} ${t.id}`} className={`mapTable pos${i+1} ${t.status} ${selected?.id===t.id?'selected':''}`} onClick={()=>choose(t)}><span>{t.id}</span></button>)}</div></div><aside className="inventory"><p className="inventoryEyebrow">TABLES & EXPERIENCES</p><h3>Choose your view.</h3>{tables.map(t=><button key={t.id} disabled={t.status==='reserved'} className={`inventoryRow ${selected?.id===t.id?'active':''}`} onClick={()=>choose(t)}><span><b>{t.name}</b><small>{t.id} · Up to {t.guests} guests</small></span><span><small>{t.status}</small><b>${t.minimum.toLocaleString()}</b></span></button>)}<button className="aiPlan" onClick={()=>setConcierge(true)}>Not sure? Ask VIP Concierge</button></aside></div></section>
<footer><div className="mark">N<span>O</span>IR</div><p>Washington, DC · A BFP Venue Intelligence demonstration.</p><div><a href="#events">Events</a><a href="#reserve">Reservations</a><a href="#">Private Events</a></div></footer>
{selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="booking" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">{activeEvent.month} {activeEvent.day} · {activeEvent.artist}</p><h2>{selected.name}</h2><p>{selected.detail}</p><div className="facts"><span><small>UP TO</small>{selected.guests} guests</span><span><small>MINIMUM SPEND</small>${selected.minimum.toLocaleString()}</span></div><div className="demoForm"><label>Guest count<select defaultValue={Math.min(selected.guests,Number(heroGuests))}>{Array.from({length:selected.guests},(_,i)=><option key={i+1}>{i+1}</option>)}</select></label><label>Occasion<select defaultValue={heroExperience==='Birthday'?'Birthday':'Night out'}><option>Night out</option><option>Birthday</option><option>Anniversary</option><option>Corporate / Client</option></select></label></div><div className="bookingActions"><button className="primary" onClick={()=>{setSelected(null);setConcierge(true);send(`I want ${selected.name} ${selected.id} for ${activeEvent.artist} for ${heroGuests} guests with ${heroExperience}. Help me complete the reservation and ask me what you still need.`)}}>Continue with concierge</button><button onClick={()=>{setSelected(null);setConcierge(true);send(`Compare ${selected.name} with the other available tables for ${activeEvent.artist}.`)}}>Compare with AI</button></div></div></div>}
{concierge&&<div className="concierge"><div className="conciergeTop"><div><small>NOIR DC / PRIVATE HOST</small><strong>VIP Concierge</strong></div><button onClick={()=>setConcierge(false)}>×</button></div><div className="chat chatLive">{messages.map((m,i)=><p key={i} className={m.role==='ai'?'ai':'userMsg'}>{m.text}</p>)}{busy&&<p className="typing">Concierge is thinking…</p>}<div className="suggestions"><button onClick={()=>send('Birthday for 10 guests')}>Birthday · 10 guests</button><button onClick={()=>send('I want to be near the DJ')}>Near the DJ</button><button onClick={()=>send('Keep the table under $2,500')}>Under $2,500</button></div></div><form className="composer" onSubmit={e=>{e.preventDefault();send()}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Tell me about your night…"/><button type="submit">↑</button></form></div>}
</main>
);
}