'use client';
import {useState} from 'react';
import {venueConfig} from '../../lib/venue-config';

const tables=[['A1','DJ Gallery','AVAILABLE','$2,500'],['A2','DJ Gallery','HOLD','$2,500'],['B1','Noir Booth','AVAILABLE','$1,800'],['B2','Noir Booth','AVAILABLE','$1,800'],['C1','Salon','RESERVED','$1,200'],['C2','Salon','AVAILABLE','$1,200']];
const reservations=[['R-1048','A. Carter','6','Birthday','C1','CONFIRMED'],['R-1049','M. Johnson','8','Night Out','A2','HOLD']];
const guests=[['A. Carter','Birthday','6','C1','11:00 PM'],['M. Johnson','Night Out','8','A2','10:45 PM']];

export default function Dashboard(){
 const [q,setQ]=useState('');
 const [reply,setReply]=useState('Tonight is looking strong. Ask me about guests, reservations, marketing, social, promoters, events or revenue.');
 const [busy,setBusy]=useState(false);
 const [view,setView]=useState('Tonight');
 const [action,setAction]=useState<any>(null);
 const [insights,setInsights]=useState<any[]>([]);
 const [brainActions,setBrainActions]=useState<any[]>([]);
 async function ask(text?:string){const v=(text||q).trim();if(!v)return;setQ('');setBusy(true);try{const r=await fetch('/api/brain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:v})});const d=await r.json();setReply(d.reply);setInsights(Array.isArray(d.insights)?d.insights:[]);setBrainActions(Array.isArray(d.actions)?d.actions:[])}finally{setBusy(false)}}
 async function runCommand(id:string){setAction({title:'RUNNING COMMAND',result:'Working across connected venue systems…',detail:'The command center is processing the requested action.'});try{const r=await fetch('/api/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:id})});const d=await r.json();setAction(d)}catch{setAction({title:'ACTION READY',result:'Command prepared',detail:'Connect the venue service to execute this action against live customer data.'})}setTimeout(()=>setAction(null),5200)}
 const nav=['Tonight','Reservations','Tables','Guests','Marketing','Social','Promoters','Events','Revenue'];
 return <main className="dash">
  <aside className="rail">
   <a href="/" className="dashLogo">{venueConfig.brand.name}<span>°</span></a>
   <div className="railNav"><b>COMMAND CENTER</b>{nav.map(n=><button key={n} className={view===n?'active':''} onClick={()=>setView(n)}>{n}</button>)}</div>
   <div className="connections"><span>{venueConfig.operations.crmLabel}</span><span>{venueConfig.operations.adsLabel}</span><span>{venueConfig.operations.socialLabel}</span></div>
   <div className="system"><i/> VENUE BRAIN ONLINE</div>
  </aside>
  <section className="dashMain">
   <header><div><small>{venueConfig.brand.city.toUpperCase()} / OWNER COMMAND CENTER</small><h1>{view==='Tonight'?'GOOD EVENING.':view.toUpperCase()+'.'}</h1></div><a href="/">VIEW LIVE SITE ↗</a></header>
   <div className="metrics"><article><small>TABLE MINIMUMS</small><strong>$3,700</strong><span>confirmed + active holds</span></article><article><small>AVAILABLE TABLES</small><strong>04</strong><span>of 6 tables</span></article><article><small>WEEKEND TICKET SALES</small><strong>668</strong><span>across 3 events</span></article><article><small>AD RESULTS</small><strong>65</strong><span>tracked results this week</span></article></div>
   <section className="brain">
    <div className="brainHead"><span>AI</span><div><small>{venueConfig.brand.name} VENUE BRAIN</small><h2>RUN THE VENUE.</h2></div></div>
    <p className="brainReply">{busy?'Reading the operation…':reply}</p>{insights.length>0&&<div className="brainInsights">{insights.map((i:any)=><article key={i.label}><small>{i.label}</small><strong>{i.value}</strong><span>{i.note}</span></article>)}</div>}{brainActions.length>0&&<div className="brainCommands">{brainActions.map((a:any)=><button key={a.id} onClick={()=>runCommand(a.id)}>{a.label} →</button>)}</div>}
    <div className="quick"><button onClick={()=>ask('What needs my attention tonight?')}>What needs attention?</button><button onClick={()=>ask('How are the ads performing?')}>How are ads doing?</button><button onClick={()=>ask('Who should we text to fill Saturday?')}>Who should we text?</button><button onClick={()=>ask('Which promoter is performing best?')}>Top promoter?</button></div>
    <form onSubmit={e=>{e.preventDefault();ask()}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask the venue brain anything…"/><button>ASK →</button></form>
   </section>

   {view==='Tonight'&&<div className="opsGrid"><TablePanel/><BookPanel/></div>}
   {view==='Tables'&&<section className="panel fullPanel"><Title eyebrow="LIVE FLOOR" title="TABLE INVENTORY" meta="CLIENT VIEW"/>{tables.map(t=><div className="tableRow" key={t[0]}><b>{t[0]}</b><span>{t[1]}</span><button className={'statusBtn '+t[2].toLowerCase()} onClick={()=>ask(`Tell me what I should do with table ${t[0]} which is ${t[2]}`)}>{t[2]}</button><strong>{t[3]}</strong></div>)}</section>}
   {view==='Reservations'&&<section className="panel fullPanel"><Title eyebrow="VIP HOST DESK" title="RESERVATIONS" action="AI SUMMARY" onAction={()=>ask('Summarize reservations and next actions')}/>{reservations.map(r=><div className="resCard" key={r[0]}><div><small>{r[0]} · TABLE {r[4]}</small><strong>{r[1]}</strong><span>{r[2]} guests · {r[3]}</span></div><div className="resActions"><em className={r[5].toLowerCase()}>{r[5]}</em><button onClick={()=>ask(`Give me the host brief for ${r[1]}`)}>HOST BRIEF</button></div></div>)}</section>}
   {view==='Guests'&&<section className="panel fullPanel"><Title eyebrow="CRM VIEW" title="VIP GUESTS" meta="NO CRM LOGIN NEEDED"/>{guests.map(g=><div className="guestRow" key={g[0]}><strong>{g[0]}</strong><span>{g[1]}</span><span>{g[2]} guests</span><span>Table {g[3]}</span><span>{g[4]}</span><button onClick={()=>ask(`What should the host know about ${g[0]} tonight?`)}>ASK AI</button></div>)}<div className="commandStrip"><button onClick={()=>runCommand('send_vip_sms')}>TEXT VIP LIST</button><button onClick={()=>runCommand('email_birthdays')}>EMAIL BIRTHDAYS</button><button onClick={()=>ask('Show me guests who have not returned recently and are worth reactivating')}>FIND REACTIVATION LIST</button></div></section>}

   {view==='Marketing'&&<section className="fullPanel"><div className="marketingTop"><div><small>PERFORMANCE ONLY</small><h3>ADS PERFORMANCE</h3><p>Your team manages targeting and optimization behind the scenes. The venue sees results, what BFP is changing, and what improved.</p></div><button className="panelAction" onClick={()=>ask('Review current ad performance and tell me what BFP should fix next')}>AI PERFORMANCE REVIEW</button></div><div className="adGrid">{venueConfig.ads.map(a=><article className="adCard" key={a.name}><div className="adCardTop"><small>{a.status}</small><strong>{a.name}</strong></div><div className="adMetrics"><span><b>${a.spend}</b><small>SPEND</small></span><span><b>{a.leads}</b><small>RESULTS</small></span><span><b>{a.tableInquiries}</b><small>TABLE LEADS</small></span><span><b>{a.ticketSales}</b><small>TICKET SALES</small></span></div><div className="optimization"><b>{a.trend}</b><span>BFP OPTIMIZATION</span><p>{a.status==='REVIEW'?'Creative fatigue detected. BFP will refresh creative and rebalance spend.':'Performing well. BFP is protecting spend and scaling the winning creative.'}</p></div></article>)}</div></section>}

   {view==='Social'&&<section className="panel fullPanel"><Title eyebrow="CONTENT ENGINE" title="SOCIAL PLANNER" action="UPLOAD CONTENT" onAction={()=>setAction({title:'CONTENT UPLOAD',result:'Media intake opened',detail:'Creative can be uploaded here and routed into the content calendar.'})}/>{venueConfig.social.map(s=><div className="socialRow" key={s.day+s.time+s.event}><div><small>{s.day} · {s.time}</small><strong>{s.event}</strong></div><span>{s.channel}</span><span>{s.type}</span><em>{s.status}</em><button onClick={()=>runCommand('queue_social')}>QUEUE</button></div>)}<div className="commandStrip"><button onClick={()=>ask('Write this week social plan around our three events')}>BUILD WEEK PLAN</button><button onClick={()=>runCommand('caption')}>GENERATE CAPTION</button><button onClick={()=>ask('What is the best time to post our next event content and why?')}>BEST TIME TO POST</button></div></section>}

   {view==='Promoters'&&<section className="panel fullPanel"><Title eyebrow="PROMOTER INTELLIGENCE" title="PROMOTER CENTER" meta="ATTRIBUTION + REVENUE"/>{venueConfig.promoters.map((p,i)=><div className="promoterRow" key={p.code}><b>#{i+1}</b><strong>{p.name}</strong><span>{p.code}</span><span>{p.guests} guests</span><span>{p.tickets} tickets</span><span>{p.tables} tables</span><em>${p.revenue.toLocaleString()}</em><button onClick={()=>ask(`Give me a performance brief for ${p.name}`)}>BRIEF</button></div>)}<div className="commandStrip"><button onClick={()=>ask('Which promoter is performing best and who needs attention?')}>AI PROMOTER REVIEW</button><button onClick={()=>runCommand('notify_promoters')}>NOTIFY PROMOTERS</button></div></section>}

   {view==='Events'&&<section className="fullPanel"><div className="eventOpsHead"><div><small>ONE EVENT → EVERY CHANNEL</small><h3>EVENT BUILDER</h3><p>Create once, then push the event into website, ticketing, social, CRM messaging and promoter workflows.</p></div><button className="panelAction" onClick={()=>setAction({title:'EVENT BUILDER',result:'New event workflow opened',detail:'Create the event once, then publish it across the website, guest messaging, social calendar and promoter workflows.'})}>+ CREATE EVENT</button></div><div className="eventOpsGrid">{venueConfig.events.map(e=><article className="eventOpsCard" key={e.id}><small>{e.date} · {e.music}</small><h4>{e.name}</h4><div><span><b>{e.ticketsSold}</b> tickets</span><span><b>${e.ticketRevenue.toLocaleString()}</b> revenue</span><span><b>{e.tableInquiries}</b> table inquiries</span></div><button onClick={()=>ask(`Give me a promotion plan for ${e.name}`)}>ASK BRAIN FOR PLAN →</button></article>)}</div></section>}

   {view==='Revenue'&&<section className="revenueGrid"><article className="revenueCard"><small>REPRESENTED TABLE MINIMUMS</small><strong>$3,700</strong><span>Confirmed + active holds</span></article><article className="revenueCard"><small>WEEKEND TICKETS</small><strong>$26.7K</strong><span>Gross ticket revenue</span></article><article className="revenueCard"><small>TOP PROMOTER REVENUE</small><strong>$9.2K</strong><span>Attributed to J. Prince</span></article><section className="panel revenueBrain"><Title eyebrow="AI REVENUE DESK" title="WHAT SHOULD WE PUSH?"/><p>Use the venue brain to identify open inventory, guest segments, promoter opportunities and marketing gaps without exposing the underlying CRM.</p><button className="panelAction" onClick={()=>ask('Based on tonight and this weekend, what should we push to maximize revenue?')}>ASK FOR REVENUE PLAN →</button></section></section>}

   {action&&<div className="actionToast"><b>{action.title||'COMMAND RESULT'}</b><span>{action.result||'Action completed'}</span><small>{action.detail||'The venue command was processed.'}</small></div>}
  </section>
 </main>
}
function Title({eyebrow,title,meta,action,onAction}:{eyebrow:string,title:string,meta?:string,action?:string,onAction?:()=>void}){return <div className="panelTitle"><div><small>{eyebrow}</small><h3>{title}</h3></div>{action?<button className="panelAction" onClick={onAction}>{action}</button>:<span>{meta}</span>}</div>}
function TablePanel(){return <section className="panel"><Title eyebrow="LIVE FLOOR" title="TABLE STATUS" meta="6 TABLES"/>{tables.map(t=><div className="tableRow" key={t[0]}><b>{t[0]}</b><span>{t[1]}</span><em className={t[2].toLowerCase()}>{t[2]}</em><strong>{t[3]}</strong></div>)}</section>}
function BookPanel(){return <section className="panel"><Title eyebrow="VIP HOST DESK" title="TONIGHT'S BOOK" meta="LIVE BOOK"/>{reservations.map(r=><div className="resCard" key={r[0]}><div><small>{r[0]} · TABLE {r[4]}</small><strong>{r[1]}</strong><span>{r[2]} guests · {r[3]}</span></div><em className={r[5].toLowerCase()}>{r[5]}</em></div>)}<div className="activity"><small>AUTOMATION STATUS</small><p>✓ Guest captured in CRM</p><p>✓ VIP host notification ready</p><p>✓ Confirmation + reminders queued</p><p>○ POS / table platform adapter ready</p></div></section>}
